upgraded to ssm

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,44 +1,95 @@
 name: Deploy to EC2
 
 on:
-    push:
-        branches: [ "main" ]
+  push:
+    branches: [ "main" ]
+
+permissions:
+  id-token: write
+  contents: read
 
 jobs:
-    deploy:
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout code
-              uses: actions/checkout@v4
+  deploy:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v5
 
-            - name: Set up Go
-              uses: actions/setup-go@v4
-              with: 
-                  go-version: '1.25.1'
-                  
-            - name: Build Go binary
-              run: |
-                 go mod tidy
-                 cd cmd/api
-                 GOOS=linux GOARCH=amd64 go build -o mealbook
-                 mv mealbook ../../mealbook 
+      - name: Setup Go
+        uses: actions/setup-go@v6
+        with:
+          go-version: '1.25.1'
+          check-latest: true
 
-            - name: Upload to EC2
-              uses: appleboy/scp-action@v0.1.4
-              with:
-                  host: ${{ secrets.EC2_HOST }}
-                  username: ${{ secrets.EC2_USER }}
-                  key: ${{ secrets.EC2_SSH_KEY }}
-                  source: "mealbook"
-                  target: "/home/${{ secrets.EC2_USER }}/"
+      - name: Build Go binary
+        run: |
+          go mod tidy
+          cd cmd/api
+          GOOS=linux GOARCH=amd64 go build -o mealbook
+          mv mealbook ../../mealbook
+      
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v5.1.0
+        with:
+          aws-region: ap-south-1
+          role-to-assume: arn:aws:iam::010438498079:role/GitHubActionsDeployRole
 
-            - name: Restart Systemd Service
-              uses: appleboy/ssh-action@v0.1.6
-              with:
-                  host: ${{ secrets.EC2_HOST }}
-                  username: ${{ secrets.EC2_USER }}
-                  key: ${{ secrets.EC2_SSH_KEY }}
-                  script: |
-                      sudo systemctl daemon-reload
-                      sudo systemctl restart mealbook.service
-                      sudo systemctl status mealbook.service --no-pager
+      - name: Upload binary to S3
+        run: |
+          aws s3 cp mealbook s3://mealbook-app-binary-s3/mealbook-latest
+          echo "Binary uploaded to S3"
+
+      - name: Deploy to EC2 via SSM
+        run: |
+          echo "Sending deployment command to EC2..."
+
+          COMMAND_ID=$(aws ssm send-command \
+          --instance-ids "i-0dad74584bdbaf5d4" \
+          --document-name "AWS-RunShellScript" \
+          --parameters 'commands=[
+            "cd /home/ubuntu",
+            "echo Downloading binary from S3...",
+            "aws s3 cp s3://mealbook-app-binary-s3/mealbook-latest ./mealbook",
+            "echo Restarting service...",
+            "sudo systemctl daemon-reload",
+            "sudo systemctl restart mealbook.service",
+            "echo Deployment complete"
+          ]' \
+          --output text \
+          --query "Command.CommandId")
+
+          echo "Command ID: $COMMAND_ID"
+          echo "Waiting for deployment to complete"
+
+          aws ssm wait command-executed \
+            --command-id "$COMMAND_ID" \
+            --instance-id "i-0dad74584bdbaf5d4"
+
+          STATUS=$(aws ssm get-command-invocation \
+          --command-id "$COMMAND_ID" \
+          --instance-id "i-0dad74584bdbaf5d4" \
+          --query "Status" \
+          --output text
+          )
+
+          if [ "$STATUS" = "Success" ]; then 
+            echo "Deployment succeeded."
+
+              echo "Output:"
+            aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "i-0dad74584bdbaf5d4" \
+              --query "StandardOutputContent" \
+              --output text
+          else
+            echo "Deployment failed!"
+            
+            # Show the error
+            aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "i-0dad74584bdbaf5d4" \
+              --query "StandardErrorContent" \
+              --output text
+            
+            exit 1
+          fi
